# Generated by Django 4.2.5 on 2025-04-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название отдела', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание отдела (необязательно)', null=True)),
                ('folder_id', models.CharField(blank=True, help_text='ID папки Google Drive', max_length=255, null=True)),
            ],
            options={
                'db_table': '"portal"."departments"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('t_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': '"portal"."linked"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('t_number', models.CharField(blank=True, max_length=50)),
                ('isadmin', models.BooleanField(default=False)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('linked_amount', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': '"portal"."users"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_app.user')),
            ],
            options={
                'db_table': '"portal"."auth_users"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDepartmentMapping',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='department_mapping', serialize=False, to='portal_app.user')),
                ('department', models.ForeignKey(blank=True, help_text='Отдел, в котором работает пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_app.department')),
            ],
            options={
                'db_table': '"portal"."user_department_mappings"',
                'managed': True,
            },
        ),
    ]
