# Generated by Django 4.2.5 on 2025-03-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('t_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('t_number', models.CharField(blank=True, max_length=50)),
                ('isadmin', models.BooleanField(default=False)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('linked_amount', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
