# Generated by Django 4.2.5 on 2025-03-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='linked',
            table='linked',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
