# Generated by Django 4.2.5 on 2025-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_alter_linked_table_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('password_hash', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'auth_users',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
