# Generated by Django 4.2.5 on 2025-04-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0005_department_alter_linked_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='folder_id',
            field=models.CharField(blank=True, help_text='ID папки Google Drive, где хранятся документы для данного отдела', max_length=255, null=True),
        ),
    ]
