# Generated by Django 4.2.5 on 2025-04-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0007_alter_authuser_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='portal.auth_users',
        ),
        migrations.AlterModelTable(
            name='department',
            table='portal.departments',
        ),
        migrations.AlterModelTable(
            name='userdepartmentmapping',
            table='portal.user_department_mappings',
        ),
    ]
