# Generated by Django 4.2.5 on 2025-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('data', models.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
